language: rust
rust:
  - stable
  - beta
  - nightly

sudo: true

before_install:
  - bin/install_libffi.sh

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
