pre-release-replacements = [
  { file="README.md", search="libffi-sys = \"[0-9.]*\"", replace="libffi-sys = \"{{version}}\"" },
  { file="src/lib.rs", search="libffi-sys = \"[0-9.]*\"", replace="libffi-sys = \"{{version}}\"" },
  { file="src/lib.rs", search="https://docs[.]rs/libffi-sys/[0-9.]*", replace="https://docs.rs/libffi-sys/{{version}}" }
]
